language: python
fast_finish: true

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

os:
  - linux

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran

before_install:
  - pip -q install coveralls

install: pip install -e .

script: coverage run tests/test.py -v

after_success: coveralls
